### ISSUE TITLE
Cocoapods not working

### ISSUE THREAD

**Issue by ghanshyammansata** [cometchat-pro/ios-chat-sdk-swift-4.2#1]

**Comment by naveengeco** [comment]
Could you please share Comet Chat Pro SDK working with Swift 4 Sample.

**Comment by bhooshanpatil** [comment]
Hello @naveengeco,
Currently, we are facing an issue with cocoa pods for swift 4.2 and below, 
but you can always integrate `CometChatPro` SDK Manually into your iOS app.
[Steps to Integrate CometChatPro Manually](https://prodocs.cometchat.com/docs/ios-setup#section-manually)

**Comment by bhooshanpatil** [comment]
We have discontinued the cocoapods support for the version lower than Swift 5.
But you can always integrate `CometChatPro` SDK Manually into your iOS app.
[Steps to Integrate CometChatPro Manually](https://prodocs.cometchat.com/docs/ios-setup#section-manually)
