### ISSUE TITLE
[SDK-Version] Issue Title Bitcode error

### ISSUE THREAD

**Issue by akhiljohny** [cometchat-pro/ios-chat-sdk-swift-4.2#4]
**Describe the bug**
Bitcode error while uploading to app store.

**To Reproduce**
2. Upload application to App store including Firebase messaging 6.6.0 version
3. Bitcode enable False

**Expected behavior**
Success email from Apple team.

**Actual behavior**
Got error email from Apple: 

**TMS-90338: Non-public API usage - The app references non-public symbols in App name: _pb_decode, _pb_encode, _pb_istream_from_buffer, _pb_ostream_from_buffer. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Best regards,

The App Store Team**

**Screenshots** (optional)

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.7]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
- Error Log
- Debug Log

**Additional context**

**Comment by akhiljohny** [comment]
is there any way to make Firebase messaging bitcode to YES and Cometchat pro bitcode to NO. ?

**Comment by pushpsenairekar2911** [comment]
Hello, It seems that this query is related to Firebase, not CometChatPro SDK. Kindly, set the bitcode enable to NO and upload the new build for your iOS app. Also, still if you face the same issue then raise the query at Firebase support.

**Comment by akhiljohny** [comment]
@pushpsenairekar2911  
Hi,  
   But if we upload without cometchat and enable bitcode true then there is no issue. Application successfully can be upload to appstore. Any way to solve this issue. I need firebase and cometchat.

**Comment by anantgarg** [comment]
@akhiljohny your issue has nothing to do with Bitcode. You can refer to something like: https://stackoverflow.com/questions/46743368/non-public-api-usage-the-app-references-non-public-symbols-xctfailureformat/46896567

**Comment by anantgarg** [comment]
@akhiljohny you'll have to check with the Firebase team on the error message you are facing when Bitcode is set to false. This is an issue on their end.

**Comment by akhiljohny** [comment]
@pushpsenairekar2911  @anantgarg 
Hi,
   I think the issue is because of script e put on run phrase. The script given in comet chat documentation is not working so I put this: 
cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
if [[ -d "Frameworks" ]]; then
rm -fr Frameworks
fi
Please help with this. I checked a lot documents and stackoverflow none helped me.

**Comment by pushpsenairekar2911** [comment]
Hello @akhiljohny, Please, try by removing the script and then upload the same on to the AppStore. There might be some dependency conflict which causing the issue.

**Comment by akhiljohny** [comment]
@pushpsenairekar2911  @anantgarg 
Helo,
      It was the issue of script. I changed it and uploaded to App store without any issue. Thank you for your help.
